name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        npm install
        npm run lint
        npm run build