name: Aisha CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Code format check
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm run lint

  build:
    needs: ['lint']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start build
      run: |
        cd $GITHUB_WORKSPACE
        npm install
        npm run build